### ISSUE TITLE
Slowing In epoch step

### ISSUE THREAD

**Issue by Sayantan17** [jacobssy/Traffic_Sign_detection#3]
Hello,  @jacobssy again buddy i successfully reached in input  Epoch steps. It is running very slowly i think GPU is not working in the code which i validated with Task manager which is using CPU & GPU is not been used. I think that your computer has good specification. What are your comp specifications. 
Help would be apprecialted.
THANK YOU again.

**Comment by jacobssy** [comment]
@Sayantan17 I use the combination of GPU &CPU from my college lab
cpu:
![image](https://user-images.githubusercontent.com/14237914/37884440-8df4f3aa-30e2-11e8-8557-f3c060ab6b26.png)

gpu:
![image](https://user-images.githubusercontent.com/14237914/37884456-a4f14144-30e2-11e8-80a3-97b4bb3c2f93.png)

I think you could lower the batch number , but it may cause a worse result, as for the GPU work ,you should checkout as the screenshot shows , you could specify the os.environ["CUDA_VISIBLE_DEVICES"],you could try it again,let me know your result. 
![image](https://user-images.githubusercontent.com/14237914/37884554-16f5795e-30e3-11e8-9f0b-3bc50c672387.png)

I am using another LISA dataset to detect traffic sign, I will update the branch if I finish that.

**Comment by Sayantan17** [comment]
@jacobssy yeah sure I will update you.

**Comment by Sayantan17** [comment]
![37884554-16f5795e-30e3-11e8-9f0b-3bc50c672387](https://user-images.githubusercontent.com/37222844/37970265-ade0e1f6-31f0-11e8-91d3-3ac2881af52b.png)
Buddy @jacobssy buddy I use AMD  520 series Graphics (laptop) please help I think that this code is for CUDA (NVIDIA) Can you help me with the code for AMD what changes are required in place of CUDA?
I think my graphic card will keep the training step slow but still please help to get it configured for my laptop so that it can use GPU & CPU both (AMD Radeon Series)

**Comment by Sayantan17** [comment]
![37884554-16f5795e-30e3-11e8-9f0b-3bc50c672387](https://user-images.githubusercontent.com/37222844/37970265-ade0e1f6-31f0-11e8-91d3-3ac2881af52b.png)
Buddy @jacobssy buddy I use AMD  520 series Graphics (laptop) please help I think that this code is for CUDA (NVIDIA) Can you help me with the code for AMD what changes are required in place of CUDA?
I think my graphic card will keep the training step slow but still please help to get it configured for my laptop so that it can use GPU & CPU both (AMD Radeon Series)
I think Theano (OPENGL) will work shall it be ? If so please help to get the code for it so that this code uses GPU.
Thank you

**Comment by jacobssy** [comment]
@Sayantan17 tensorflow only support NVIDIA(CUDA), not support AMD now.. The computing backend  I use is tensorflow, even switch to the Theano, It seems not to support AMD well, here is the link https://stackoverflow.com/questions/27971707/using-pythontheano-with-opencl-in-an-amd-gpu
maybe you should consider other solution... you could rent GPU cloud, I suppose

**Comment by Sayantan17** [comment]
@jacobssy I m planning to change my laptop ; will 940 (NVidia)MX be okay for these Deep learning ?

**Comment by jacobssy** [comment]
@Sayantan17  I suppose it is ok, my labtop  is Nvidia TITAN(PASCAL), it could run that well, my memory is 12G, so if your laptop has limited memory, you should lower the batch value(the more batch you use, the more memory consume )make sure resource usage is fine.

**Comment by Sayantan17** [comment]
Sure I will try.

**Comment by Sayantan17** [comment]
@jacobssy I m plannin' to buy a decent price laptop can you help which of these 1. Nvidia 940 MX vs 2. MX 150  or MX 130 will be better for deep learning so that it will help in future work.
Thanks

**Comment by jacobssy** [comment]
@Sayantan17  In my view, MX 150 is a good choice ,but if the memory is limited, the difference is not so obvious, as for me, in the same level of  price , I prefer to have a GPU with more memory, because in deep learning filed, the batch parameter is very important, you should ensure you have enough memory to load the data(to most people, it is a trouble to devise a data generator,we always load all batch data in every min-batch ), so I recommend to purchase the GPU with more memory.
BTW,I am not a specialist in hardware, I just state my view  according to  my  usage experience ;)

**Comment by Sayantan17** [comment]
@jacobssy  buddy I got new laptop with GeForce MX-150 & My semester exams are near & will start work after one month & will keep in touch through email & we will discuss issues after one month.
Thanks

**Comment by Sayantan17** [comment]
@jacobssy hello

**Comment by Sayantan17** [comment]
@jacobssy  I have got  my laptop can u tell how to test the code for making sure that my GPU is working properly or not in the code of detection?
