### ISSUE TITLE
Model weights?

### ISSUE THREAD

**Issue by omearac** [jacobssy/Traffic_Sign_detection#4]
Great project! I was wondering if you could attach the model weights you trained?

**Comment by jacobssy** [comment]
@omearac Hi :) I am not sure which weights do you point,but I am sorry fo missing the weights in this repo, the weights of classify  is 154M, the weights of detection is 579M without compression, and I save them all in our laboratory computers cluster,it has limited access. I will upload them soon , and let you know the progress status

**Comment by jacobssy** [comment]
@omearac  I have uploaded the model weights in https://pan.baidu.com/s/1S1bj6lgRDUNgjcK_iS0qHg
which needs no secret key, including 4 model files, you could download them without downloading the app,just through the web service

**Comment by omearac** [comment]
perfect thanks! Yes I meant the weights after training the network for the sign detection. I have limited time/cloud resources to train the model and my results are okay but I believe from your plot output that your model had more time/epochs to train. I for example so far only used 11 epochs. Thanks!

**Comment by teaddicted** [comment]
@jacobssy I was wondering if you could upload the model weights on google drive or something because the baidu link has expired. Thanks!

**Comment by jacobssy** [comment]
@teaddicted I have created a new baidu drive link  :https://pan.baidu.com/s/18Ed-J2YyX4gc3EgxhzHG3A

**Comment by lenkele** [comment]
Hi, great job!
Very interesting to test your weight. I can not acsess baidu disk. I will be very grateful if you could put the weight on google drive. 
Thanks!

**Comment by jacobssy** [comment]
@lenkele ok , I will send u the notice when i finish the data upload

**Comment by lenkele** [comment]
@jacobssy , many thanks!

**Comment by jacobssy** [comment]
@lenkele  u can download from here https://drive.google.com/drive/folders/1wzzYSzAOmzF7qTUTjdKuTm5dwYl-VYWU?usp=sharing

**Comment by lenkele** [comment]
@jacobssy Thank you, I'v I downloaded!

**Comment by gonelove31** [comment]
Just tried https://baidufast.com/ and it actually works pretty well. They give  for free. Honestly, that’s pretty cheap compared to most of these services.
